version: "3.1"

services:
    mongo:
        image: mongo:7.0.6
        container_name: diw-mongo
        restart: always
        environment:
            MONGO_INITDB_DATABASE: bbdd
        ports:
            - '27017:27017'
        volumes:
            - vue-mongo:/data/db

volumes:
    vue-mongo: